// Generated by Wrangler on Fri Jun 14 2024 07:46:18 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	SUDOS: KVNamespace;
	RPC_URL: string;
	NETWORK_PASSPHRASE: string;
	TEST_SK: string;
	NATIVE_CONTRACT_ID: string;
	FUND_SK: string;
	JWT_SECRET: string;
	ENV: string;
	CREDITS_DURABLE_OBJECT: DurableObjectNamespace;
	SEQUENCER_DURABLE_OBJECT: DurableObjectNamespace;
	DB: D1Database;
}
