// Generated by Wrangler on Mon Jun 24 2024 19:05:36 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	SUDOS: KVNamespace;
	RPC_URL: string;
	NETWORK_PASSPHRASE: string;
	TEST_SK: string;
	NATIVE_CONTRACT_ID: string;
	FUND_SK: string;
	JWT_SECRET: string;
	ENV: string;
	CREDITS_DURABLE_OBJECT: DurableObjectNamespace;
	SEQUENCER_DURABLE_OBJECT: DurableObjectNamespace;
	DB: D1Database;
}
