// Generated by Wrangler on Tue May 28 2024 15:36:20 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	SUDOS: KVNamespace;
	FEEBUMP_SK: string;
	JWT_SECRET: string;
	FEEBUMP_DURABLE_OBJECT: DurableObjectNamespace;
}
